modules.button1.onEvent(jacdac.ButtonEvent.Down, function () {
    modules.led1.setPixelColor(0, 0x000000)
    mySprite.startEffect(effects.spray)
    mySprite.setVelocity(50, 50)
})
modules.button4.onEvent(jacdac.ButtonEvent.Down, function () {
    modules.led1.setPixelColor(0, 0xff0000)
    sprites.destroy(mySprite)
})
let mySprite: Sprite = null
mySprite = sprites.create(img`
    ........................
    ......ffff..............
    ....fff22fff............
    ...fff2222fff...........
    ..fffeeeeeefff..........
    ..ffe222222eef..........
    ..fe2ffffff2ef..........
    ..ffffeeeeffff..........
    .ffefbf44fbfeff.........
    .fee41fddf14eef.........
    fdfeeddddd4eff..........
    fbffee444edd4e..........
    fbf4f2222edde...........
    fcf.f22cccee............
    .ff.f44cdc4f............
    ....fffddcff............
    .....fddcff.............
    ....cddc................
    ....cdc.................
    ....cc..................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
mySprite.setPosition(43, 37)
mySprite.setBounceOnWall(true)
scaling.scaleToPercent(mySprite, 150, ScaleDirection.Uniformly, ScaleAnchor.Middle)
controller.moveSprite(mySprite)
